name: PR - Lint and Test

on:
  pull_request:
    branches:
      - main
env:
  PROJECT_ID: squid-apis

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup & Cache Node Modules
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install
        run: npm install

      - name: Lint
        run: npm lint

      - name: Test
        run: npm test